import { User, Client, Case, Task, Document, Note, UserRole, CaseStatus, TaskStatus, TaskPriority } from '../types'

// Default test users
export const mockUsers: User[] = [
  {
    id: 1,
    email: 'owner@firm.com',
    full_name: 'John Owner',
    role: UserRole.OWNER,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    email: 'lawyer@firm.com',
    full_name: 'Sarah Lawyer',
    role: UserRole.LAWYER,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    email: 'assistant@firm.com',
    full_name: 'Mike Assistant',
    role: UserRole.ASSISTANT,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const mockClients: Client[] = [
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    address: '123 Main St, City, State 12345',
    is_active: true,
    created_at: new Date(2024, 0, 15).toISOString(),
    updated_at: new Date(2024, 1, 10).toISOString(),
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane.doe@email.com',
    phone: '(555) 234-5678',
    address: '456 Oak Ave, City, State 12345',
    is_active: true,
    created_at: new Date(2024, 0, 20).toISOString(),
    updated_at: new Date(2024, 1, 15).toISOString(),
  },
  {
    id: 3,
    name: 'ABC Corporation',
    email: 'contact@abccorp.com',
    phone: '(555) 345-6789',
    address: '789 Business Blvd, City, State 12345',
    is_active: true,
    created_at: new Date(2024, 1, 1).toISOString(),
    updated_at: new Date(2024, 1, 20).toISOString(),
  },
]

export const mockCases: Case[] = [
  {
    id: 1,
    case_number: 'CASE-2024-001',
    title: 'Smith v. Insurance Co.',
    description: 'Personal injury case involving a car accident. Client seeking compensation for medical expenses and lost wages.',
    case_type: 'Personal Injury',
    status: CaseStatus.IN_PROGRESS,
    client_id: 1,
    primary_attorney_id: 2,
    opened_date: '2024-01-15',
    next_hearing_date: '2024-03-15',
    statute_of_limitations: '2025-01-15',
    created_at: new Date(2024, 0, 15).toISOString(),
    updated_at: new Date(2024, 1, 10).toISOString(),
    client: mockClients[0],
    primary_attorney: mockUsers[1],
  },
  {
    id: 2,
    case_number: 'CASE-2024-002',
    title: 'Doe Employment Dispute',
    description: 'Employment discrimination case. Client alleges wrongful termination based on protected characteristics.',
    case_type: 'Employment Law',
    status: CaseStatus.OPEN,
    client_id: 2,
    primary_attorney_id: 2,
    opened_date: '2024-01-20',
    next_hearing_date: '2024-04-01',
    created_at: new Date(2024, 0, 20).toISOString(),
    updated_at: new Date(2024, 1, 5).toISOString(),
    client: mockClients[1],
    primary_attorney: mockUsers[1],
  },
  {
    id: 3,
    case_number: 'CASE-2024-003',
    title: 'ABC Corp Contract Review',
    description: 'Contract negotiation and review for corporate client.',
    case_type: 'Corporate Law',
    status: CaseStatus.OPEN,
    client_id: 3,
    primary_attorney_id: 2,
    opened_date: '2024-02-01',
    created_at: new Date(2024, 1, 1).toISOString(),
    updated_at: new Date(2024, 1, 1).toISOString(),
    client: mockClients[2],
    primary_attorney: mockUsers[1],
  },
]

export const mockTasks: Task[] = [
  {
    id: 1,
    title: 'Review medical records',
    description: 'Review all medical records from the accident',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    due_date: '2024-02-20',
    case_id: 1,
    assignee_id: 3,
    created_by_id: 2,
    created_at: new Date(2024, 1, 1).toISOString(),
    case: mockCases[0],
    assignee: mockUsers[2],
    creator: mockUsers[1],
  },
  {
    id: 2,
    title: 'File motion for discovery',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    due_date: '2024-02-15',
    case_id: 1,
    assignee_id: 2,
    created_by_id: 2,
    created_at: new Date(2024, 1, 5).toISOString(),
    case: mockCases[0],
    assignee: mockUsers[1],
    creator: mockUsers[1],
  },
  {
    id: 3,
    title: 'Draft response to defendant',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    due_date: '2024-02-25',
    case_id: 2,
    assignee_id: 3,
    created_by_id: 2,
    created_at: new Date(2024, 1, 10).toISOString(),
    case: mockCases[1],
    assignee: mockUsers[2],
    creator: mockUsers[1],
  },
  {
    id: 4,
    title: 'Schedule deposition',
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    due_date: '2024-02-10',
    case_id: 1,
    assignee_id: 3,
    created_by_id: 2,
    created_at: new Date(2024, 0, 20).toISOString(),
    completed_at: new Date(2024, 1, 10).toISOString(),
    case: mockCases[0],
    assignee: mockUsers[2],
    creator: mockUsers[1],
  },
  {
    id: 5,
    title: 'Review contract terms',
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    due_date: '2024-03-01',
    case_id: 3,
    assignee_id: 2,
    created_by_id: 2,
    created_at: new Date(2024, 1, 15).toISOString(),
    case: mockCases[2],
    assignee: mockUsers[1],
    creator: mockUsers[1],
  },
]

export const mockDocuments: Document[] = [
  {
    id: 1,
    name: 'Medical Report - Dr. Johnson.pdf',
    file_path: '/documents/medical-report-1.pdf',
    file_type: 'pdf',
    document_type: 'Medical Report',
    file_size: 245760,
    case_id: 1,
    uploaded_by_id: 3,
    uploaded_at: new Date(2024, 1, 5).toISOString(),
    uploaded_by: mockUsers[2],
  },
  {
    id: 2,
    name: 'Police Report.pdf',
    file_path: '/documents/police-report-1.pdf',
    file_type: 'pdf',
    document_type: 'Legal Document',
    file_size: 189440,
    case_id: 1,
    uploaded_by_id: 2,
    uploaded_at: new Date(2024, 1, 8).toISOString(),
    uploaded_by: mockUsers[1],
  },
  {
    id: 3,
    name: 'Employment Contract.docx',
    file_path: '/documents/employment-contract-1.docx',
    file_type: 'docx',
    document_type: 'Legal Document',
    file_size: 98304,
    case_id: 2,
    uploaded_by_id: 2,
    uploaded_at: new Date(2024, 1, 12).toISOString(),
    uploaded_by: mockUsers[1],
  },
]

export const mockNotes: Note[] = [
  {
    id: 1,
    content: 'Client called to provide additional information about the accident. Witness contact information received.',
    case_id: 1,
    author_id: 2,
    is_pinned: true,
    created_at: new Date(2024, 1, 10).toISOString(),
    author: mockUsers[1],
  },
  {
    id: 2,
    content: 'Medical records review completed. Found significant documentation of injuries.',
    case_id: 1,
    author_id: 3,
    is_pinned: false,
    created_at: new Date(2024, 1, 12).toISOString(),
    author: mockUsers[2],
  },
  {
    id: 3,
    content: 'Initial consultation completed. Client understands the process and timeline.',
    case_id: 2,
    author_id: 2,
    is_pinned: false,
    created_at: new Date(2024, 1, 20).toISOString(),
    author: mockUsers[1],
  },
]

// Helper function to simulate API delay
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))




